Bakery/ViewModels/HomeViewModel.cs
using Bakery.Models;
using System.Collections;
using System.Collections.Generic;

namespace Bakery.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Product> favProduct { get; set; }
    }
}

Bakery/ViewModels/ProductListViewModel.cs
using Bakery.Models;
using System.Collections.Generic;

namespace Bakery.ViewModels
{
    public class ProductListViewModel
    {
        public IEnumerable<Product> getAllProducts { get; set; }
        public string currCategory { get; set; }
    }
}

Bakery/ViewModels/ShopProductViewModel.cs
using Bakery.Backend.Models;

namespace Bakery.ViewModels
{
    public class ShopProductViewModel
    {
        public ShopProducts shopProducts { get; set; }
    }
}

Bakery/Controllers/HomeController.cs
using Bakery.Interfaces;
using Bakery.Models;
using Bakery.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Bakery.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAllProducts _productRep;

        public HomeController(IAllProducts productRep)
        {
            _productRep = productRep;
        }

        public ViewResult Index()
        {
            var homeProduct = new HomeViewModel
            {
                favProduct = _productRep.GetFavProducts
            };
            return View(homeProduct);
        }
    }
}

Bakery/Controllers/ProductsController.cs
using Bakery.Interfaces;
using Bakery.Models;
using Bakery.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Bakery.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IAllProducts _allProducts;
        private readonly IProductCategory _productCategory;

        public ProductsController(IAllProducts iAllProducts, IProductCategory iProductCategory)
        {
            _allProducts = iAllProducts;
            _productCategory = iProductCategory;
        }

        [Route("Product/List")]
        [Route("Product/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Product> products = null;
            string currCategory = "";
            if(string.IsNullOrEmpty(_category))
            {
                products = _allProducts.Products.OrderBy(i => i.Id);
            }
            else
            {
                if (string.Equals("Bread", category, StringComparison.OrdinalIgnoreCase))
                {
                    products = _allProducts.Products.Where(i => i.Category.categoryName.Equals("Хлеб")).OrderBy(i => i.Id);
                    currCategory = "Свежий хлеб";
                }
                else
                {
                    if (string.Equals("ForTea", category, StringComparison.OrdinalIgnoreCase))
                    {
                        products = _allProducts.Products.Where(i => i.Category.categoryName.Equals("К чаю")).OrderBy(i => i.Id);
                        currCategory = "К чаю";
                    }
                }
            }

            var productObj = new ProductListViewModel
            {
                getAllProducts = products,
                currCategory = currCategory,
            };

            return View(productObj);
        }
    }
}

Bakery/Controllers/ShopProductController.cs
using Bakery.Backend.Models;
using Bakery.Interfaces;
using Bakery.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Bakery.Controllers
{
    public class ShopProductController : Controller
    {
        private readonly IAllProducts _productRep;
        private readonly ShopProducts _shopProducts;

        public ShopProductController(IAllProducts productRep, ShopProducts shopProducts)
        {
            _productRep = productRep;
            _shopProducts = shopProducts; 
        }

        public ViewResult Index()
        {
            var items = _shopProducts.getShopItems();
            _shopProducts.listShopItem = items;

            var obj = new ShopProductViewModel
            {
                shopProducts = _shopProducts
            };
            return View(obj);
        }

        public RedirectToActionResult addToProduct(int id)
        {
            var item = _productRep.Products.FirstOrDefault(i => i.Id == id);
            if (item != null)
            {
                _shopProducts.AddToProduct(item);
            }

            return RedirectToAction("Index");
        }
    }
}

Bakery/Views/Home/Index.cshtml
@model HomeViewModel

@{
    ViewData["Title"] = "Пекарня";
}

<h3 align="center">Популярные товары</h3>
<div class="row mt-5 mb-2">
    @{
        foreach(Product product in Model.favProduct)
        {
             @Html.Partial("AllProductPage", product);
        }
    }
</div>

Bakery/Views/Products/List.cshtml
@using Bakery.ViewModels
@model ProductListViewModel

@{
    Layout = "_Layout";
    ViewData["Title"] = "Товары";
}

<h3 align="center">@Model.currCategory</h3>

<div class="row mt-5 mb-2">
    @{
        foreach (Product product in Model.getAllProducts)
        {
            @Html.Partial("AllProductPage", product);
        }
    }
</div>

Bakery/Views/Shared/AllProductsPage.cshtml
@model Product
<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.img" alt="@Model.Name">
    <h3 align="center">@Model.Name</h3>
    <p align="center">Цена: @Model.Price.ToString("c")</p>
    <p><a class="btn btn-warning" asp-controller="ShopProduct" asp-action="AddToProduct" asp-route-id="@Model.Id">Добавить в корзину</a></p>
</div>

Bakery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bakery</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link active" href="/Product/List">Товары</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="/Product/List/Bread">Хлеб</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link active" href="/Product/List/ForTea">К чаю</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link active" href="/ShopProduct/Index">Корзина</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Bakery
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Bakery/Views/ShopProduct/Index.cshtml
@using Bakery.ViewModels
@model ShopProductViewModel

@{
    ViewData["Title"] = "Корзина";
}
@{ 
    double totalCoast = 0;
}
<div class="container">
    @foreach  (var el in Model.shopProducts.listShopItem)
    {
            <div class = "alert  alert-warning mt-3">
                <b>Товар:</b> @el.product.Name<br />
                <b>Цена:</b> @el.product.Price.ToString("c")
            </div>
        totalCoast += el.product.Price;
    }
    <hr />

    <b>Общая стоимость заказа: @totalCoast.ToString("c")</b>
    <hr />

    <a class="btn btn-danger" asp-controller="Order" asp-action="Checkout">Оплатить</a>
</div>